<?xml version="1.0"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<project default="compile" name="cyclonedx">

  <!-- easy way to override properties -->
  <property file="build.properties"/>

  <target name="ready-to-package" depends="common.ready-to-package">
    <copy todir="${build.classes}/org/apache/ant/cyclonedx">
      <file file="version.properties"/>
    </copy>
  </target>

  <target name="ready-to-compile" depends="setup,resolve">
    <path id="classpath.compile.extra">
      <path refid="ivy.lib.path"/>
    </path>
    <path id="classpath.test.extra">
      <path refid="ivy.lib.path"/>
    </path>
  </target>

  <target name="fetch-cyclonedx" depends="antlib">
    <condition property="can.use.cyclonedx">
      <isset property="jdk9+"/>
    </condition>
    <condition property="add.ant.core.component">
      <isset property="jdk9+"/>
    </condition>
    <classloader name="cdx.loader" parentName="antlib.classloader.ivy">
      <classpath>
        <path refid="classpath.compile"/>
        <pathelement location="${jarname}"/>
      </classpath>
    </classloader>
    <typedef uri="antlib:org.apache.ant.cyclonedx"
             resource="org/apache/ant/cyclonedx/antlib.xml"
             loaderRef="cdx.loader"/>
  </target>

  <target name="antunit-test" depends="ready-to-test-with-antunit,resolve"
    unless="skip-antunit">
    <condition property="antunit.includes" value="${antunit.testcase}"
               else="**/test.xml,**/*-test.xml">
      <isset property="antunit.testcase" />
    </condition>

    <property name="antunit.excludes" value="" />

    <mkdir dir="${antunit.report.dir}" />

    <path id="ivy-plus-cdx">
      <path refid="classpath.test"/>
      <path refid="classpath.test.extra"/>
      <pathelement location="${build.classes}"/>
    </path>
    <au:antunit xmlns:au="antlib:org.apache.ant.antunit"
      failOnError="false"
      errorProperty="antunit.tests.failed"
      >
      <classpath>
        <path refid="ivy-plus-cdx"/>
      </classpath>
      <fileset dir="${src.antunit}" includes="${antunit.includes}"
               excludes="${antunit.excludes}" />

      <au:xmllistener todir="${antunit.report.dir}" />
      <au:plainlistener/>
      <referenceset>
        <reference refid="classpath.test"/>
        <reference refid="ivy-plus-cdx"/>
      </referenceset>
      <propertyset>
        <propertyref name="antlib.location"/>
      </propertyset>
    </au:antunit>
  </target>

  <target name="define-cyclonedx-components"
          depends="define-core-ant-components"
          if="can.use.cyclonedx"
          xmlns:cdx="antlib:org.apache.ant.cyclonedx">
    <cdx:externalreferenceset
        id="antlib-ext-refs">
      <externalReference
          type="VCS"
          url="https://gitbox.apache.org/repos/asf/ant-antlibs-cyclonedx.git"/>
      <externalReference
          type="ISSUE_TRACKER"
          url="https://bz.apache.org/bugzilla/buglist.cgi?component=CycloneDX%20Antlib&amp;product=Ant"/>
      <externalReference
          type="DOCUMENTATION"
          url="https://ant.apache.org/antlibs/cyclonedx/manual/"/>
    </cdx:externalreferenceset>
  </target>

  <!-- overridden until common/cyclonedx.xml supports compositionAggregate -->
  <target name="define-core-ant-components"
          if="add.ant.core.component"
          xmlns:cdx="antlib:org.apache.ant.cyclonedx"
          depends="define-common-cyclonedx-references">
    <cdx:component
        name="ant-launcher"
        group="org.apache.ant"
        version="${ant.core.version}"
        isExternal="true"
        compositionAggregate="complete"
        id="ant-launcher">
      <supplier refid="ant-pmc"/>
      <license refid="apache-2"/>
      <externalReferenceSet refid="ant-common-refs"/>
      <externalReferenceSet refid="ant-ext-refs"/>
    </cdx:component>
    <cdx:component
        name="ant"
        group="org.apache.ant"
        version="${ant.core.version}"
        isExternal="true"
        compositionAggregate="complete"
        id="ant">
      <supplier refid="ant-pmc"/>
      <license refid="apache-2"/>
      <externalReferenceSet refid="ant-common-refs"/>
      <externalReferenceSet refid="ant-ext-refs"/>
      <dependency componentRef="ant-launcher"/>
    </cdx:component>
  </target>

  <target name="create-antlib-sbom"
          depends="define-cyclonedx-components"
          if="can.use.cyclonedx"
          xmlns:cdx="antlib:org.apache.ant.cyclonedx">
    <uptodate property="antlib-sbom-ok"
              targetfile="${build.lib}/${artifact.stub}.cdx.json">
      <srcresources>
        <file file="${jarname}"/>
        <file file="ivy.xml"/>
        <file file="build.xml"/>
      </srcresources>
    </uptodate>
    <cdx:componentbom
        bomName="${artifact.stub}.cdx"
        outputdirectory="${build.lib}"
        format="all"
        useComponentSupplier="true"
        useComponentManufacturer="true"
        unless:set="antlib-sbom-ok"
        xmlns:unless="ant:unless">
      <component
          description="Apache CycloneDX Antlib"
          publisher="The Apache Software Foundation"
          supplierIsManufacturer="true"
          compositionAggregate="complete">
        <cdx:ivyModule conf="default,provided" externalConf="provided">
          <templateComponent refid="ant"/>
          <templateComponent refid="ant-launcher"/>
          <templateComponent
              name="ivy"
              group="org.apache.ivy"
              publisher="The Apache Software Foundation"
              description="Apache Ivy"
              supplierIsManufacturer="true"
              compositionAggregate="complete">
            <supplier refid="ant-pmc"/>
            <license refid="apache-2"/>
            <externalReferenceSet refid="ant-common-refs"/>
            <externalReference
                type="MAILING_LIST"
                url="https://ant.apache.org/ivy/mailing-lists.html"/>
            <externalReference
                type="VCS"
                url="https://gitbox.apache.org/repos/asf/ant-ivy.git"/>
            <externalReference
                type="ISSUE_TRACKER"
                url="http://issues.apache.org/jira/browse/IVY"/>
            <externalReference
                type="DISTRIBUTION"
                url="https://ant.apache.org/ivy/download.cgi"/>
            <externalReference
                type="SOURCE_DISTRIBUTION"
                url="https://ant.apache.org/ivy/download.cgi"/>
            <externalReference
                type="ADVISORIES"
                url="https://ant.apache.org/ivy/security.html"/>
          </templateComponent>
        </cdx:ivyModule>
        <file file="${jarname}"/>
        <supplier refid="ant-pmc"/>
        <license refid="apache-2"/>
        <externalReferenceSet refid="ant-common-refs"/>
        <externalReferenceSet refid="antlibs-common-ext-refs"/>
        <externalReferenceSet refid="antlib-ext-refs"/>
      </component>
      <license refid="apache-2"/>
    </cdx:componentbom>
  </target>

  <target name="ready-for-bin-dist" depends="create-antlib-sbom,common.ready-for-bin-dist"/>

  <target name="after-dist"
          depends="define-cyclonedx-components"
          if="can.use.cyclonedx">
    <macrodef name="create-tarball-bom">
      <attribute name="distdir"/>
      <attribute name="distbase"/>
      <attribute name="subdir"/>
      <attribute name="binsrc"/>
      <attribute name="binarysource"/>
      <attribute name="ext"/>
      <element name="moreComponentChildren" implicit="true" optional="true"/>
      <sequential>
        <cdx:archivebom
            outputdirectory="@{distbase}"
            archiveVersion="${artifact.version}"
            bomName="${dist.name}-@{binsrc}.@{ext}.cdx"
            purl="https://archive.apache.org/dist/ant/antlibs/cyclonedx/@{subdir}/${dist.name}-@{binsrc}.@{ext}"
            archiveLocation="@{distbase}/${dist.name}-@{binsrc}.@{ext}"
            description="Apache CycloneDX Antlib @{binarysource}"
            publisher="The Apache Software Foundation"
            xmlns:cdx="antlib:org.apache.ant.cyclonedx">
          <additionalComponentChildren>
            <supplier refid="ant-pmc"/>
            <license refid="apache-2"/>
            <externalReferenceSet refid="ant-common-refs"/>
            <externalReferenceSet refid="antlibs-common-ext-refs"/>
            <externalReferenceSet refid="antlib-ext-refs"/>
            <moreComponentChildren/>
          </additionalComponentChildren>
          <archiveContent>
            <fileset dir="@{distdir}/..">
              <include name="${dist.name}/**"/>
            </fileset>
          </archiveContent>
          <additionalBomContent>
            <license refid="apache-2"/>
          </additionalBomContent>
        </cdx:archivebom>
      </sequential>
    </macrodef>
    <macrodef name="create-tarball-boms">
      <attribute name="distdir"/>
      <attribute name="distbase"/>
      <attribute name="subdir"/>
      <attribute name="binsrc"/>
      <attribute name="binarysource"/>
      <element name="componentChildren" implicit="true" optional="true"/>
      <sequential>
        <create-tarball-bom
            distdir="@{distdir}"
            distbase="@{distbase}"
            subdir="@{subdir}"
            binsrc="@{binsrc}"
            binarysource="@{binarysource}"
            ext="tar.gz">
          <componentChildren/>
        </create-tarball-bom>
        <create-tarball-bom
            distdir="@{distdir}"
            distbase="@{distbase}"
            subdir="@{subdir}"
            binsrc="@{binsrc}"
            binarysource="@{binarysource}"
            ext="tar.bz2">
          <componentChildren/>
        </create-tarball-bom>
        <create-tarball-bom
            distdir="@{distdir}"
            distbase="@{distbase}"
            subdir="@{subdir}"
            binsrc="@{binsrc}"
            binarysource="@{binarysource}"
            ext="zip">
          <componentChildren/>
        </create-tarball-bom>
      </sequential>
    </macrodef>
  </target>

  <target name="after-src-dist" depends="after-dist" if="can.use.cyclonedx">
    <create-tarball-boms
        distdir="${src.dist.dir}"
        distbase="${dist.base}"
        subdir="source"
        binsrc="src"
        binarysource="Source Distribution"/>
  </target>

  <target name="after-bin-dist" depends="after-dist"
          if="can.use.cyclonedx"
          xmlns:cdx="antlib:org.apache.ant.cyclonedx">
    <create-tarball-boms
        distdir="${bin.dist.dir}"
        distbase="${dist.base}"
        subdir="binaries"
        binsrc="bin"
        binarysource="Binary Distribution">
      <component>
        <cdx:sbomLink createBomExternalReference="false">
          <file file="${bin.dist.dir}/${artifact.stub}.cdx.json"/>
        </cdx:sbomLink>
        <file file="${bin.dist.dir}/${artifact.stub}.jar"/>
      </component>
    </create-tarball-boms>
  </target>

  <target name="after-fat-bin-dist" depends="after-dist"
          if="can.use.cyclonedx"
          xmlns:cdx="antlib:org.apache.ant.cyclonedx">
    <create-tarball-boms
        distdir="${bin.dist.dir}"
        distbase="${dist.base}"
        subdir="binaries"
        binsrc="bin-withdeps"
        binarysource="Binary Distribution Including Dependencies">
      <component>
        <cdx:sbomLink createBomExternalReference="false">
          <file file="${bin.dist.dir}/${artifact.stub}.cdx.json"/>
        </cdx:sbomLink>
        <file file="${bin.dist.dir}/${artifact.stub}.jar"/>
      </component>
    </create-tarball-boms>
  </target>

  <import file="common/build.xml"/>
</project>
